---
name: fnlfmt
description: Formatter for Fennel code
homepage: https://git.sr.ht/~technomancy/fnlfmt
licenses:
  - MIT
languages:
  - Fennel
categories:
  - Formatter

source:
  # renovate:datasource=git-tags
  id: pkg:generic/https://git.sr.ht/~technomancy/fnlfmt@0.3.2
  download:
    files:
      fnlfmt-{{version}}.tar.gz: https://git.sr.ht/~technomancy/fnlfmt/archive/{{version}}.tar.gz
  build:
    run: make
    bin: fnlfmt

bin:
  fnlfmt: "{{source.build.bin}}"