---
name: fnlfmt
description: Formatter for Fennel code
homepage: https://git.sr.ht/~technomancy/fnlfmt
licenses:
  - MIT
languages:
  - Fennel
categories:
  - Formatter

source:
  # renovate:datasource=git-tags
  id: pkg:generic/https://git.sr.ht/~technomancy/fnlfmt@0.3.2
  build:
    env:
      URL: "https://git.sr.ht/~technomancy/fnlfmt/archive/{{version}}.tar.gz"
    run: |
      curl -L -o fnlfmt.tar.gz "$URL"
      tar --no-same-owner -xvf fnlfmt.tar.gz
      cd fnlfmt-*
      echo "#!/usr/bin/env lua" > fnlfmt
      LUA_PATH="./?.lua" ./fennel --require-as-include --compile cli.fnl >> fnlfmt
      chmod +x fnlfmt 

bin:
  fnlfmt: "fnlfmt-{{version}}/fnlfmt"
